### ISSUE TITLE
Add tags to new portfolio studies

### ISSUE THREAD

**Issue by jakejohns** [virtualredhead/red.portfolio#16]
- [ASC]( https://github.com/virtualredhead/red.portfolio/blob/develop/data/asc/study.yaml#L6)
- [ELI](https://github.com/virtualredhead/red.portfolio/blob/develop/data/eli/study.yaml#L6)
- [ICHD](https://github.com/virtualredhead/red.portfolio/blob/develop/data/ichd-women/study.yaml#L6)

**Comment by allisonraeck** [comment]
ASC: Brand development and campaign development
ELI: Web development and design
ICHD: Campaign development and marketing strategy
