### ISSUE TITLE
https://staging.redhead.studio/studies/crl - swap s4.jpg with cover photo

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.portfolio#26]
swap these two images
![s1](https://user-images.githubusercontent.com/38866201/103701546-30e44900-4f74-11eb-95fd-336dade13c33.jpg)
![s4](https://user-images.githubusercontent.com/38866201/103701547-32157600-4f74-11eb-8272-6fc69ba3d874.jpg)

**Comment by jakejohns** [comment]
77eef719651667f0101523b5e1e59adb7e76c161
