### ISSUE TITLE
RFS Case Study - Content

### ISSUE THREAD

**Issue by allisonraeck** [virtualredhead/red.portfolio#38]
**Michigan State University Center for Regional Food Systems**

Campaign development, marketing strategy

Creating a campaign to get child care providers excited about growing and eating local foods with their little ones. 

[GrowMoreMI.org](http://growmoremi.org/)

**Understanding the big-picture goal**
When executed correctly, a creative campaign can be a win-win for the client and audiences alike. With “Grow More,” we worked to achieve this goal. The Michigan Farm to Early Care and Education (ECE) initiative — led by Michigan State University Center for Regional Food Systems — helps children ages birth-5 years and their families eat more local foods by offering resources and connections for child care providers, programs, and preschools. To encourage child care providers and the children in their care to consume and grow local, nutrient-dense foods, the Center sought a targeted social marketing campaign, “Grow More,”  that balanced encouragement with education. Funders for the campaign specified that this would specifically target the Battle Creek, Detroit, and Grand Rapids markets, aiming to reach providers in urban communities that historically faced more limited access to grow and consume local produce. 

**Finding a style that resonates**
First, we developed options for the “Grow More” campaign’s distinct creative direction and style, which would go on to inform subsequent material production. When brainstorming, we considered child care providers’ unique perspectives and needs, ultimately identifying the social-emotional impact of eating and growing local foods as a key selling point. Thus, a bright, uplifting visual tone and the “Happiness is homegrown” tagline were born. Next, we created a full-scale marketing plan for the center, which included tactics specific to the campaign as well as broader marketing initiatives for the center to implement in the long term. We then narrowed this marketing plan into a distinct Campaign Plan for “Grow More” itself, working with the client to pinpoint which strategies would have the greatest impact and ROI. 

**Delivering on audiences’ needs**
When selecting mediums for the campaign, we knew we needed to meet our target audience where they were. Because child care providers are often pressed for time and resources, we developed strategies that would help support their capacity with tools that they would actually use. Deliverables included a website, printable activity pages, informational downloads, social shareables, a badge, a letter, targeted emails, and outreach to local partners, such as farmers markets. Arguably most exciting, however, was a mailed “Little Sprouts Learning Bundle” package for providers, which included seeds, a decal, activity sheets, and information to get them excited about eating and growing local. With this bundle, providers would not only be inspired to identify as part of the campaign’s movement, but to take actionable steps to immediately start growing and expanding the campaign’s messaging to the little ones in their care. (And, of course, it allowed for some very, very cute vegetable illustrations.)

**Comment by moe-ferland** [comment]
RFS Case Study Visuals:
![RFS_section-4](https://github.com/virtualredhead/red.portfolio/assets/141849347/c5a3a0c8-4660-49b0-b5d6-6cf5dab888fe)
![RFS_thumbnail](https://github.com/virtualredhead/red.portfolio/assets/141849347/cd0d3386-a17a-44df-a461-da8a1786635f)
![RFS_section-1](https://github.com/virtualredhead/red.portfolio/assets/141849347/2eabe5b5-e8a2-4814-adef-42d3974c4b78)
![RFS_section-2](https://github.com/virtualredhead/red.portfolio/assets/141849347/db4fd5c6-a2b0-4c3f-a8f1-27c10826d8f6)

**Comment by allisonraeck** [comment]
@tonybredhead These visuals are reordered above 
1. activity sheets
2. sticker
3. desktop
4. phone

**Comment by tonybredhead** [comment]
Images are reordered
