### ISSUE TITLE
PT Case Study - Content

### ISSUE THREAD

**Issue by allisonraeck** [virtualredhead/red.portfolio#39]
**MSU Department of Pharmacology and Toxicology**

Web development, design, content development

Aligning a content-dense, academic website with a cutting-edge, innovative persona. 

[phmtox.msu.edu](https://phmtox.msu.edu/)

**Out with the old, in with the new**
Your website is a reflection of your organization’s culture. It is your first impression, and an extension of yourself. For that reason, Michigan State University’s Department of Pharmacology and Toxicology sought an updated website that better reflected its persona and achievements. While the department was on the cutting-edge and contributed to breakthrough scientific discoveries, its previous website’s outdated design and organization did not portray this. Therefore, we sought to develop a website that prioritized the user experience and was on-par with MSU web standards, paired with aesthetically driven design and content that mindfully propelled the department’s goals and identity. 

**Finding harmony in hierarchy**
To start, we completed a full web audit of the site, evaluating all pages and identifying those that could be moved, adjusted, or eliminated. We outlined a strategic web hierarchy with the target audience’s flow in mind, driving users toward the department’s different objectives for varying customer journeys. Within our new hierarchy, we emphasized the department’s new focus toward promoting research, which came into play through a dedicated section filtered by fields and an updated “News” module. Across all pages, we also streamlined content, removing redundancies and incorporating a written tone that more closely aligned with the department’s brand, including some catchy marketing-centric headlines to guide the audience forward.  

**A streamlined user experience**
[The final website](http://phmtox.msu.edu/) was a well-organized home base to showcase the department’s research, people, and accomplishments to both internal and external audiences. The site’s design and content represented the culture and tone of the department, without having to overtly state “culture” on its own page, as it was previously. Together, strategic web development, design, and content more effectively emphasized the research, academics, core facilities, and news from the department, streamlining the user experience for numerous audiences and increasing web traffic. As the department moves forward to continue groundbreaking research and stand as a leader in its field, its website will now be able to support that momentum.

**Comment by allisonraeck** [comment]
![PT_section1](https://github.com/virtualredhead/red.2021/assets/141849347/03502442-d873-46ac-a355-26b79557dec5)
![PT_section2](https://github.com/virtualredhead/red.2021/assets/141849347/4e32ee9f-d95c-49ef-8568-0e4cfd4f8b2c)
![PT_section3](https://github.com/virtualredhead/red.2021/assets/141849347/053877e8-c2e0-4d69-802e-91c31f784f3b)
![PT_section4](https://github.com/virtualredhead/red.2021/assets/141849347/b43cec4c-a524-47ba-977c-dfcd8a2b6b96)
![PT_thumbnail_copy](https://github.com/virtualredhead/red.2021/assets/141849347/d4041ce6-4a0b-4f6d-a2a5-9d71fb406e0a)
![PT_thumbnail](https://github.com/virtualredhead/red.2021/assets/141849347/09ddc63d-91f0-4e0b-b3d1-577dfb3c57bc)

**Comment by kelglass** [comment]
@tonybredhead 
new photos: [pt-mockups.zip](https://github.com/virtualredhead/red.portfolio/files/14885479/pt-mockups.zip)
please keep the current thumbnail and the image of two phones side by side (make it img 2 please). replace the rest. I think these ones do a slightly better job at showing some of the different things we did for the site

**Comment by tonybredhead** [comment]
All set on this
