### ISSUE TITLE
READABILITY: BAH. Look at the navigation

### ISSUE THREAD

**Issue by Rachak66** [virtualredhead/red.portfolio#5]
![screen shot 2018-10-01 at 2 42 57 pm](https://user-images.githubusercontent.com/11648286/46308705-5b225180-c588-11e8-9584-54bcde3eae5a.png)

**Comment by jillfreitas** [comment]
Is this better?
![wilson-cover2](https://user-images.githubusercontent.com/25016552/46351932-907d7c80-c626-11e8-9346-bfd7f23e78e6.jpg)
